import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { CartProvider } from "./context/CartContext";
 
import { ReactNode } from 'react'; // Import ReactNode for typing children  
 // Update with the correct import paths  


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
interface Props {  
  children: ReactNode;  
}  
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MyComponent: React.FC<Props> = ({ children }) => {  
  return (  
    <html lang="en">  
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>  
        {children} {/* This will render any child elements passed to MyComponent */}  
      </body>  
    </html>  
  );  
};  
  